<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0">
  <modelVersion>4.0.0</modelVersion>
  <groupId>org.example</groupId>
  <artifactId>sample-service</artifactId>
  <dependencies>
    <dependency>
      <groupId>org.example.lumen</groupId>
      <artifactId>lumen-core-starter-web</artifactId>
    </dependency>
    <dependency>
      <groupId>io.tidewater</groupId>
      <artifactId>tw-client</artifactId>
    </dependency>
  </dependencies>
  <build>
    <plugins>
      <plugin>
        <groupId>org.example.build</groupId>
        <artifactId>quarry-maven-plugin</artifactId>
      </plugin>
    </plugins>
  </build>
</project>
